### PR TITLE
Add big red button

### LINKED ISSUE #99: Add a big-red-button

### PR DESCRIPTION
**Pull request by andraskvr**
# Description

closes #99 

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [x] Attached issue to pull request
- [x] Changelog entry
- [x] Code is clear and sufficiently documented
- [ ] ~Sufficient test cases (reproduces the bug/tests the requested feature)~
- [x] Correct, in line with design
- [ ] ~End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )~

# Reviewer Checklist:

- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Code is clear and sufficiently documented
- [ ] Correct, in line with design

### CODE REVIEW

**Comment by bartv** [comment]
Looks good, however I do not have a setup to easily see it. So if someone can post an enabled / disabled screenshot that would be great!

**Review by wouterdb — APPROVED** [review]

**Comment by wouterdb** [comment]
it looks a bit weird, perhaps it should be in line with the status button, and less big (figuratively big red button is sufficient, I think) 
perhaps even drop the text and only keep the symbol

**Comment by wouterdb** [comment]
when clicking unpause agent when halted, the dashboard goes:

image

**Comment by wouterdb** [comment]
resume should require confirmation as well as stop, I think. 
The resume operation is more dangerous on than the stop

**Review by wouterdb — CHANGES_REQUESTED** [review]
see comments

**Comment by bartv** [comment]
I agree about the visual. I would place it inline with the connected button. If required the connected button could be reduced to the checkmark + a tooltip.

I am also not sure that halt and resume are sufficiently clear. I would keep the analogy with these types of buttons:
https://www.google.com/search?q=emergency+stop&sxsrf=ALeKk03v-WjM983kROMPYO6K8MdBZzv08w:1599460700102&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjVk_K2t9brAhWB2aQKHduFB4UQ_AUoAXoECBQQAw&biw=1912&bih=2049

I am unable to find this icon (+ it might not be that known in it). However, I would not use the pause icon because it really is a stop and not a pause like in the agent page. 

- I think that  glyphicon-stop would work better here and use stop / resume. The icon for resume is fine.
- Use the same type button as the connected button
- Use the terms "stop" and "resume". In the tooltip I would like to also see "emergency stop"

**Review by bartv — CHANGES_REQUESTED** [review]
see my other comment

**Comment by wouterdb** [comment]
image
image

**Review by wouterdb — APPROVED** [review]

**Review by bartv — APPROVED** [review]

**Pull request merged**
